---
development:
  cloud_name: dki1yhtzy
  api_key: '681446483616253'
  api_secret: EsiuQLPtnmKawI5lNjeaOUbEstI
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dki1yhtzy
  api_key: '681446483616253'
  api_secret: EsiuQLPtnmKawI5lNjeaOUbEstI
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dki1yhtzy
  api_key: '681446483616253'
  api_secret: EsiuQLPtnmKawI5lNjeaOUbEstI
  enhance_image_tag: true
  static_image_support: false
